defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:
  run:
    dir: .
  output_subdir: null
  sweep:
    dir: .
    subdir: .


## User Setting ##
input_img_dir: 'input/PNEUMONIA/person1946_bacteria_4874.jpeg'
output_img_dir: 'output/image/ggc.png'
output_multi_img_dir: 'output/image/ggc_multi.png'
model_dir: 'models/convnext_base.pth'
target: 0


## Model ##
model_name: 'convnext_base'
num_classes: 2


## Transform ##
image_size: 224


## Visualization ##
# https://captum.ai/api/utilities.html#captum.attr.visualization.visualize_image_attr
vis_img:
  enable: True
  method: 'blended_heat_map'
  sign: 'absolute_value'
  plt_fig_axis:
  outlier_perc: 2
  cmap:
  alpha_overlay: 0.5
  show_colorbar: False
  title:
  fig_size: [6, 6]
  use_pyplot: True


# https://captum.ai/api/utilities.html#captum.attr.visualization.visualize_image_attr_multiple
vis_img_multi:
  enable: False
  methods: ["heat_map", "original_image"]
  signs: ["absolute_value", "all"]
  titles:
  fig_size: [6, 6]
  use_pyplot:
  show_colorbar: True
  alpha_overlay:
  cmap:


## Algorithm ##

# Guided Grad-CAM
# !!! 
ggc:
  device_ids:
  additional_forward_args:
  interpolate_mode: 'nearest'
  attribute_to_layer_input: False