defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:
  run:
    dir: .
  output_subdir: null
  sweep:
    dir: .
    subdir: .


## User Setting ##
input_img_dir: 'input/PNEUMONIA/person1946_bacteria_4874.jpeg'
output_img_dir: 'output/image/ggc_multi.png'
model_dir: 'models/convnext_base.pth'
target: 0


## Model ##
model_name: 'convnext_base'
num_classes: 2


## Transform ##
image_size: 224


## Visualization ##
vis_img:
  enable: True


vis_img_multi:
  enable: True


## Algorithm ##

# Guided Grad-CAM
ggc:
  device_ids: None
  additional_forward_args: None # (any, optional, default: None)
  interpolate_mode: 'nearest' # (str, optional, default: 'nearest')
  attribute_to_layer_input: False # (bool, optional, default: False)